### ISSUE TITLE
6502 Firmware for 16k rom

### ISSUE THREAD

**Issue by linuxplayground** [sillycowvalley/Hopper#18]
Hi there,  I was wondering if you had a 16k build for the 6502 handy.  My breadboard computer has 4x16k banks of rom and I was hoping to try out Hopper on one of them.  I watched your 8k minimal video, but couldn't figure out from it which options to exclude in the build process and not generate errors.

Here is a clean build:
```
➜  Assembly git:(main) ✗ cat build.sh 
/home/davelatham/projects/6502/vasm-mirror/vasm6502_oldstyle \
    -dotdir \
    -wdc02 \
    -Fbin Hopper/Hopper.asm \
    -I ./Firmware \
    -L Output/Listings/Hopper.lst \
    -o Output/Binary/Hopper.out
➜  Assembly git:(main) ✗ ./build.sh 
vasm 1.9f (c) in 2002-2023 Volker Barthelmann
vasm 6502 cpu backend 0.12 (c) 2002,2006,2008-2012,2014-2023 Frank Wille
vasm oldstyle syntax module 0.19a (c) 2002-2023 Frank Wille
vasm binary output module 2.3a (c) 2002-2023 Volker Barthelmann and Frank Wille

org0001:8000(acrwx1):	           0 bytes
org0002:8400(acrwx1):	       22626 bytes
org0003:fffa(acrwx1):	           0 bytes
org0004:8000(acrwx1):	         878 bytes
org0005:fff0(acrwx1):	           4 bytes
org0006:fffa(acrwx1):	           6 bytes
```

Running on ubuntu for now.  I know to use windows for when it's up and running on my board.  That's no problem.

I also thought it might be fun to try it out on my commander x16.  There the rom banks are 16k too.  Except I don't have the serial card for it.  SO that will have to wait.

Oh - and the discord link seems to have expired.  Any chance of a new one?

If I can figure out how to get the firmware up I might take notes and put together a readme on how to port a hopper runtime to a custom 6502 board.  As far as I can tell the minimum requirements are a 6502, ACIA (mines a rockwell 6551) and a VIA.  

I wonder how hard it would be to port this lot over to the CC65 Assembler.  Hmmm.  Okay one step at a time...

Chur!

Dave (from Auckland)

**Comment by sillycowvalley** [comment]
Hey Dave,

Here's a fresh discord invite:
https://discord.gg/QmZ68cmQ

The current version of the Hopper minimal runtime for the 6502 is written in my own dialect of assembly so the easiest way to build it is in the Hopper environment (which currently only runs on Windows .. but I have a plan to get it running on macOS and Linux .. eventually via Terminal.Gui and .NET Core).  I did write an earlier version last year using more traditional tools but that experience is what lead me to creating Hopper 6502 Assembly. In case you haven't seen it, this speaks to my motivations:
https://www.youtube.com/watch?v=IgsI51yiMoQ

You could live without the VIA (GPIO pins, Millis and Delay APIs depend on it). 6821 is tested (65uino) and I typically use the 65C22.

I currently support 2 serial options ("Apple I" is emulation only):
https://github.com/sillycowvalley/Hopper/tree/main/Source/Runtime/6502/Devices
Last year I also played with the  6551 driver but that was pre-Hopper:
https://www.hackster.io/michael-cartwright/rs232-using-a-rockwell-r6551ap-acia-with-a-6502-computer-59aecb
I do highly recommend the 6850 via FTDI now - much easier to work with since it doesn't have the Tx (?) flag buffer (and you can skip the MAX232 step):
https://www.hackster.io/michael-cartwright/rs232-using-the-motorola-6850-acia-with-a-6502-computer-33ea36

On discord we can chat about your memory layout (where to .org the ROM and where your IO chips are). I've built a 6502 emulator (also in the Hopper environment) and we can emulate your hardware config to save some to-and-fro cycles.

Regards,
Michael (splitting my time between Nelson, NZ and Blackheath, NSW)

**Comment by sillycowvalley** [comment]
FYI: this is the old v1 version from last year, not recommended or supported:
https://github.com/sillycowvalley/Hopper/tree/main/Source/6502

This is the new Minimal Runtime (currently ~12K including the slow longs and floats and a pretty good implementation of the list and record types):
https://github.com/sillycowvalley/Hopper/blob/main/Source/Runtime/r6502.asm

**Comment by linuxplayground** [comment]
I use a simple ftdi serial adapter USB at the moment with my R6551. Works great. No max323. Even if I did go that route, I don't have any PCs at home with traditional RS232 com ports on them anyway. 

I posted in #65c02 on discord.

**Comment by sillycowvalley** [comment]
Taking this discussion to discord ..
